name: Auto-generate README

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Run the README generator
      run: python generate_readme.py

    - name: Commit updated README
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Action"
        git add README.md
        # Only commit if there were changes
        git diff --cached --quiet || git commit -m "Auto-update README with latest icons"

    - name: Push changes
      uses: ad-m/github-push-action@v0.8.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}